/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _LoginRoute } from '../pages/login';
import { Route as _TransactionsRoute } from '../pages/transactions';
import { Route as _AnalysisRoute } from '../pages/analysis';
import { Route as _DealNewRoute } from '../pages/deal-new';
import { Route as _BudgetSettingsRoute } from '../pages/budget-settings';
import { Route as _MembersRoute } from '../pages/members';
import { Route as _CategorySettingsRoute } from '../pages/category-settings';
import { Route as _AccountRoute } from '../pages/account';
import { Route as _NotificationsRoute } from '../pages/notifications';
import { Route as _MoreRoute } from '../pages/more';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/login': (typeof _LoginRoute)['_inputType'];
    '/transactions': (typeof _TransactionsRoute)['_inputType'];
    '/analysis': (typeof _AnalysisRoute)['_inputType'];
    '/deal-new': (typeof _DealNewRoute)['_inputType'];
    '/budget-settings': (typeof _BudgetSettingsRoute)['_inputType'];
    '/members': (typeof _MembersRoute)['_inputType'];
    '/category-settings': (typeof _CategorySettingsRoute)['_inputType'];
    '/account': (typeof _AccountRoute)['_inputType'];
    '/notifications': (typeof _NotificationsRoute)['_inputType'];
    '/more': (typeof _MoreRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/login': (typeof _LoginRoute)['_outputType'];
    '/transactions': (typeof _TransactionsRoute)['_outputType'];
    '/analysis': (typeof _AnalysisRoute)['_outputType'];
    '/deal-new': (typeof _DealNewRoute)['_outputType'];
    '/budget-settings': (typeof _BudgetSettingsRoute)['_outputType'];
    '/members': (typeof _MembersRoute)['_outputType'];
    '/category-settings': (typeof _CategorySettingsRoute)['_outputType'];
    '/account': (typeof _AccountRoute)['_outputType'];
    '/notifications': (typeof _NotificationsRoute)['_outputType'];
    '/more': (typeof _MoreRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
