/* eslint-disable */
// This file is auto-generated by @granite-js/react-native. DO NOT EDIT.
import { Route as _AboutRoute } from '../pages/about';
import { Route as _LoginRoute } from '../pages/login';
import { Route as _IndexRoute } from '../pages/';

declare module '@granite-js/react-native' {
  interface RegisterScreenInput {
    '/about': (typeof _AboutRoute)['_inputType'];
    '/login': (typeof _LoginRoute)['_inputType'];
    '/': (typeof _IndexRoute)['_inputType'];
  }

  interface RegisterScreen {
    '/about': (typeof _AboutRoute)['_outputType'];
    '/login': (typeof _LoginRoute)['_outputType'];
    '/': (typeof _IndexRoute)['_outputType'];
  }
}
